name: '532_Spotify_Popularity'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - pip
pip:
    - dash-vega-components
